version: 2
jobs:
  setup:
    working_directory: ~/baby-dictionary/workspace
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: workspace

  build_deploy:
    working_directory: ~/baby-dictionary
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ~/baby-dictionary/workspace
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: npm run deploy


workflows:
  version: 2
  setup_build_deploy:
    jobs:
      - setup
      - build_deploy:
          requires:
            - setup
          filters:
            branches:
              only: master